title: FSMLIB
description: A lightweight, header-only C++ library for performing operations on fixed-size matrices.
author: Enrico Fraccaroli
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
social:
  email: enrico.fraccaroli@univr.it
