name: MacOS

# Trigger the workflow on push or pull requests for main and develop branches
on:
  push:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/macos.yml'
  pull_request:
    branches:
    - main
    - develop
    paths:
    - '**/*.c'
    - '**/*.cpp'
    - '**/*.h'
    - '**/*.hpp'
    - '**/CMakeLists.txt'
    - '**/Makefile'
    - '**/cmake/**'
    - '.github/workflows/macos.yml'

jobs:
  build:
    name: Build and Test (macOS)
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        include: [
          { cc: clang-9, cxx: clang-9++, label: "CLANG 9" },
          { cc: gcc-8, cxx: g++-8, label: "GCC 8" }
        ]

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GCC (if applicable)
        if: matrix.cc == 'gcc-8'
        run: |
          brew update
          brew install gcc@8
          echo "CC=gcc-8" >> $GITHUB_ENV
          echo "CXX=g++-8" >> $GITHUB_ENV

      - name: Configure Project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_C_COMPILER=${{ env.CC }} -DCMAKE_CXX_COMPILER=${{ env.CXX }} -DBUILD_TESTS=ON -DWARNINGS_AS_ERRORS=ON ..

      - name: Build Project
        run: |
          cd build
          cmake --build . --parallel 2

      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --verbose
